[package]
name = "xsv"
version = "0.9.14"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "A high performance CSV command line toolkit."
documentation = "http://burntsushi.net/rustdoc/xsv/"
homepage = "https://github.com/BurntSushi/xsv"
repository = "https://github.com/BurntSushi/xsv"
readme = "README.md"
keywords = ["csv", "tsv", "slice", "command"]
license = "Unlicense/MIT"

[[bin]]
name = "xsv"
test = false
bench = false
doctest = false

[[test]]
name = "tests"

[profile.release]
opt-level = 3

[profile.test]
opt-level = 3

[dependencies]
byteorder = "0.5"
chan = "0.1"
csv = "0.14"
docopt = "0.6"
filetime = "0.1"
num_cpus = "1.0"
rand = "0.3"
regex = "0.1"
rustc-serialize = "0.3"
streaming-stats = "0.1"
tabwriter = "0.1"
threadpool = "1.3"

[dev-dependencies]
quickcheck = "0.3"
log = "0.3"
