[package]
name = "xsv"
version = "0.9.7"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "A high performance CSV command line toolkit."
documentation = "http://burntsushi.net/rustdoc/xsv/"
homepage = "https://github.com/BurntSushi/xsv"
repository = "https://github.com/BurntSushi/xsv"
readme = "README.md"
keywords = ["csv", "tsv", "slice", "command"]
license = "Unlicense/MIT"

[[bin]]
name = "xsv"
test = false
bench = false
doctest = false

[[test]]
name = "tests"

[profile.release]
opt-level = 3

[profile.test]
opt-level = 2

[dependencies]
byteorder = "*"
chan = "0.1"
csv = "*"
docopt = "*"
filetime = "*"
libc = "*"
rand = "*"
regex = "*"
rustc-serialize = "*"
streaming-stats = "*"
tabwriter = "*"
threadpool = "*"

[dev-dependencies]
quickcheck = "*"
log = "*"

# [dependencies.csv]
# path = "/home/andrew/rust/csv"
# git = "git://github.com/BurntSushi/rust-csv"

# [dependencies.streaming-stats]
# path = "/home/andrew/data/projects/rust/streaming-stats"
# git = "git://github.com/BurntSushi/rust-stats"
#
# [dependencies.tabwriter]
# path = "/home/andrew/data/projects/rust/tabwriter"
# git = "git://github.com/BurntSushi/tabwriter"
#
# [dependencies.docopt]
# path = "/home/andrew/data/projects/rust/docopt"
# git = "git://github.com/docopt/docopt.rs"
#

# [dev-dependencies.quickcheck]
# version = "*"
# path = "/home/andrew/rust/quickcheck"
