[package]
name = "xsv"
version = "0.9.10"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "A high performance CSV command line toolkit."
documentation = "http://burntsushi.net/rustdoc/xsv/"
homepage = "https://github.com/BurntSushi/xsv"
repository = "https://github.com/BurntSushi/xsv"
readme = "README.md"
keywords = ["csv", "tsv", "slice", "command"]
license = "Unlicense/MIT"

[[bin]]
name = "xsv"
test = false
bench = false
doctest = false

[[test]]
name = "tests"

[profile.release]
opt-level = 3

[profile.test]
opt-level = 2

[dependencies]
byteorder = "0.3"
chan = "0.1"
csv = "0.14"
docopt = "0.6"
filetime = "0.1"
libc = "0.2"
rand = "0.3"
regex = "0.1"
rustc-serialize = "0.3"
streaming-stats = "0.1"
tabwriter = "0.1"
threadpool = "0.1"

[dev-dependencies]
quickcheck = "0.2"
log = "0.3"

# [dependencies.csv]
# path = "/home/andrew/rust/csv"
# git = "git://github.com/BurntSushi/rust-csv"

# [dependencies.streaming-stats]
# path = "/home/andrew/data/projects/rust/streaming-stats"
# git = "git://github.com/BurntSushi/rust-stats"
#
# [dependencies.tabwriter]
# path = "/home/andrew/data/projects/rust/tabwriter"
# git = "git://github.com/BurntSushi/tabwriter"
#
# [dependencies.docopt]
# path = "/home/andrew/data/projects/rust/docopt"
# git = "git://github.com/docopt/docopt.rs"
#

# [dev-dependencies.quickcheck]
# version = "*"
# path = "/home/andrew/rust/quickcheck"
